config/routes.rb
Rails.application.routes.draw do

  resources :preset_colors
  resources :lights do
    collection do
      post :multi_update
      post :reset_lights
      post :turn_all_on
      post :turn_all_off
      post :party_on_off
    end
  end

  resources :admin do
    collection do
      post :lock
    end
  end

  resources :sse_update do
    collection do
    end
  end

  post "lights/:id/turn_off" => "lights#turn_off"
  post "lights/:id/turn_on" => "lights#turn_on"
  post "lights/:id/switch_on_off" => "lights#switch_on_off"

  post 'lock' => 'admin#lock'

  get "/auth/account", as: :signin
  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get 'signout' => 'sessions#destroy', as: :signout

  root 'lights#index'
end

app/views/admin/_footer.html.erb
<footer class='container'>
	<div>
		<%= link_to("Home", "/", class: 'button') %>
		<%= link_to((is_locked? ? "Unĺock" : "Lock"), lock_path(lock: !is_locked?), method: :post, class: 'button') %>
  </div>
</footer>

app/views/admin/_log_list.html.erb
<!-- _log_list.html.erb-->
<% @log_entries.each do |log_entry| %>
	<tr>
		<td> <%= log_entry.created_at %> </td>
		<td> <%= log_entry.cid %> </td>
		<td> <%= log_entry.change %> </td>
	</tr>
<% end %>

app/views/admin/index.html.erb
<main class="container">
	<div>
		<table class="log-table stack">
			<thead>
				<tr>
					<th data-field="time"> Time </th>
					<th data-field="cid"> CID </th>
					<th data-field="entry"> Entry </th>
				</tr>
			</thead>
			<tbody>
				<%= render partial: 'log_list' %>
			</tbody>
		</table>
		<%= will_paginate @log_entries, renderer: FoundationPagination::Rails %>
	</div>
</main>

<%= render partial: 'footer' %>