config/routes.rb
Rails.application.routes.draw do

  resources :preset_colors
  resources :lights do
    collection do
      post :multi_update
      post :reset_lights
      post :turn_all_on
      post :turn_all_off
      post :party_on_off
    end
  end

  resources :admin do
    collection do
      post :lock
    end
  end

  resources :sse_update do
    collection do
    end
  end

  post "lights/:id/turn_off" => "lights#turn_off"
  post "lights/:id/turn_on" => "lights#turn_on"
  post "lights/:id/switch_on_off" => "lights#switch_on_off"

  post 'lock' => 'admin#lock'

  get "/auth/account", as: :signin
  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get 'signout' => 'sessions#destroy', as: :signout

  root 'lights#index'
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController
   include AdminHelper
   include PartyHelper

   before_action :set_lights_and_preset_colors, except: [:turn_on, :turn_off, :party_on_off]
   before_action :set_bulb_from_id, only: [:turn_off, :turn_on, :switch_on_off]
   before_action :check_lock_state, except: [:index]
   before_action :ruin_party, except: [:index, :party_on_off, :party_off, :party_on]

   def change_logger
      @@change_logger ||= Logger.new("#{Rails.root}/log/change.log")
   end


   #Creates sites
   def index
   end

   def lights
   end

   #Changes lights
   def multi_update
      if params[:lights]
         lights = params[:lights].keys.map(&:to_i).map { |id| get_lights.find { |l| l.id == id } }.select(&:on)

         sat = params[:saturation].to_i
         hue = params[:hue].to_i
         bri = params[:brightness].to_i

         group = Huey::Group.new lights
         group.update(sat: sat, hue: hue, bri: bri)
         changedLights = lights.map(&:id).join(" ")

         log "Lamps ##{changedLights} color changed to hue: #{hue} sat: #{sat} bri: #{bri}"
      end
      render :lights
   end

   #Set standard light
   def reset_lights
      @lights.update on: true, rgb: '#cff974', bri: 254

      log "All lamps reset"
      render :lights
   end

   def turn_off
      @light.update(on: false)
      head :ok, content_type: "text/html"
   end

   def turn_on
      @light.update(on: true)
      head :ok, content_type: "text/html"
   end

   def turn_all_off
      @lights.update(on: false)

      log "All lights OFF"
      render :lights
   end

   def turn_all_on
      @lights.update(on: true)

      log "All lights ON"
      render :lights
   end
   #Toggles light state
   def switch_on_off
      @light.on = !@light.on
      @light.save
      log "Lamp ##{params[:id]} toggled"
      render :lights
   end

   def party_on_off
      if $is_party_on
         party_off
      else
         party_on
      end
      head :ok, content_type: "text/html"
   end

   private
   def log change
      entry = LogEntry.new
      @user = current_user
      entry.cid = @user.cid + ": " + @user.to_s
      entry.change = change
      entry.save
      entry
   end

   def party_on
      entry = log "PARTY MODE ENGAGED :DDDDD"
      $is_party_on = true

      Thread.new do
         lights = get_lights

         hue_array, sat_array, bri_array = get_saved_light_arrays

         colors = [0, 5000, 15000, 20000, 42000, 55000, 62000]
         delay = 1
         while $is_party_on
            pattern = party_patterns.sample
            pattern.call lights, colors, delay
         end

         lights.each_with_index do |light, i|
            light.update sat: sat_array[i], hue: hue_array[i], bri: bri_array[i]
            sleep delay
         end

      end
   end

   def party_patterns
      [
         method(:random_bulb_and_color),
         method(:one_at_a_time_in_order),
         method(:one_color_down_both_lanes),
         method(:all_bulbs_same_color),
         method(:random_color_in_order)
      ]
   end

   def get_saved_light_arrays
      hue_array = Array.new
      sat_array = Array.new
      bri_array = Array.new

      get_lights.each_with_index do |light, i|
         hue_array[i] = light.hue
         sat_array[i] = light.sat
         bri_array[i] = light.bri
      end
      return hue_array, sat_array, bri_array
   end

   def party_off
      log "no more party :("
      $is_party_on = false
   end

   def ruin_party
      # other actions should disable party mode
      if $is_party_on
         party_off
      end
   end

   def set_bulb_from_id
      @light = get_lights.find { |l| l.id == params[:id].to_i }
   end

   def set_lights_and_preset_colors
      @lights = get_lights
      @preset_colors = PresetColor.all
   end

   def get_lights
      begin
         $hue_not_found ||= false
         unless $hue_not_found
            Huey::Bulb.all
         else
            mock_lights
         end
      rescue Huey::Errors::CouldNotFindHue
         $hue_not_found = true
         mock_lights
      end
   end

   def mock_lights
      Huey::Group.new(
         mock_bulb(7),
         mock_bulb(2),
         mock_bulb(3),
         mock_bulb(4),
         mock_bulb(5),
         mock_bulb(6)
      )
   end

   def light_response(id = "1", name = "Living Room")
     {id => {"state"=>{"on"=>true, "bri"=>127, "hue"=>54418, "sat"=>158, "xy"=>[0.509, 0.4149], "ct"=>459, "alert"=>"none", "effect"=>"none", "colormode"=>"hue", "reachable"=>true}, "type"=>"Extended color light", "name"=>name, "modelid"=>"LCT001", "swversion"=>"65003148", "pointsymbol"=>{"1"=>"none", "2"=>"none", "3"=>"none", "4"=>"none", "5"=>"none", "6"=>"none", "7"=>"none", "8"=>"none"}}}
   end

   def mock_bulb(id = "1", name = "Living Room")
     light = light_response(id, name)
     Huey::Bulb.new(light.keys.first, light.values.first)
   end
end

app/helpers/lights_helper.rb
module LightsHelper
  def find_light id_to_find
    @lights.find { |light| light.id == id_to_find }
  end
end

app/views/lights/_bulb_controls.html.erb
<!-- Requires an local value of i passed when rendering the partial like:-->
<!-- render partial: 'bulb_controls', locals: {i: a number} -->

<div class="light-row center-content">
  <div class="switch">
    <%= check_box_tag "switch_#{light.id}", 'on/off', light.on,
            onclick:"switchOnOff(#{light.id});", name: nil, class: "switch-input" %>
    <label for=<%="switch_#{light.id}"%> class="switch-paddle" >
      <span class="switch-active" aria-hidden="true">On</span>
      <span class="switch-inactive" aria-hidden="true">Off</span>
    </label>
  </div>
  <%= content_tag :div, nil, id: "color_shower_#{light.id}", class: "bulb shadow", data: {light_id: light.id} %>
  <div class="custom-checkbox">
    <%= check_box_tag "lights[#{light.id}]", '', false, class: 'checkbox' %>
    <%= label_tag "lights[#{light.id}]", "Select" %>
  </div>
</div>

app/views/lights/_button_actions.html.erb
<div class="actions button-actions-container">
  <%= button_tag "On all", data: {url: turn_all_on_lights_path}, class: "link-btn button bar-button" %>
  <%= button_tag "Off all", data: {url: turn_all_off_lights_path}, class: "link-btn button bar-button" %>
  <%= button_tag "PARTY", data: {url: party_on_off_lights_path}, class: "party-button link-btn button bar-button" %>
  <%= button_tag "Reset all", data: {url: reset_lights_lights_path}, class: "link-btn button secondary bar-button"%>
  <% if current_user.in_group?(@group.to_s) || current_user.admin? %>
    <%= link_to "Administration", '/admin', remote: false, class: "button bar-button" %>
  <% end %>
</div>

app/views/lights/_form.html.erb
<%= render partial: 'button_actions' %>

<%= form_tag(multi_update_lights_path, remote:true, id: 'hue-form') do %>

    <div class="actions light-actions">
        <%= render partial: 'lights_list' %>
    </div>

    <div class="preset-color-list actions">
    </div>

    <%= render partial: 'slider_actions' %>

<% end %>

app/views/lights/_lights_list.html.erb
<!-- _lights_list.erb-->
<div class="button-actions-container">
  <%= label_tag "Select all", "Select all", class: "button bar-button", id: "select_all_btn" %>
  <%= label_tag "Toggle selection", "Toggle selection", class: "button bar-button", id: "toggle_all_btn" %>
  <%= label_tag "Deselect all", "Deselect all", class: "button bar-button", id: "deselect_all_btn" %>
</div>
<div class="light-rows">
  <% [4, 7, 5, 2, 6, 3].each do |i| %>
      <%= render partial: 'bulb_controls', locals: {light: find_light(i)} %>
  <% end %>
</div>

app/views/lights/_slider_actions.html.erb
<div class="actions end">
  <div>
    <%= label_tag "Saturation (of color)"%>
    <div class="sat-show slider-bg range-slider">
      <%= range_field_tag :saturation, 134, in: 0..254, class: 'update clicked'%>
    </div>
  </div>
  <div>
    <%= label_tag "Hue value (of color)" %>
    <div class="hue-show slider-bg range-slider">
      <%= range_field_tag :hue, 14184, in: 0..65535, class: 'update clicked'%>
    </div>
  </div>
  <div>
    <%= label_tag "Brightness (of bulbs)"%>
    <div class="bri-show slider-bg range-slider">
      <%= range_field_tag :brightness, 254,in: 0..254, class: 'update clicked'%>
    </div>
  </div>
  <div class="right">
    <%= button_tag "Add Preset Color", class: "button", id: "add-preset-color" %>
    <%= submit_tag "Update selected bulbs' color", class: "button submit", id: "change_btn" %>
  </div>
</div>

app/views/lights/index.html.erb
<main>
	<% content_for :headJavascript do %>
		<script>
			let lights = <%= @lights.to_json.html_safe %>
			let isPartyOn = <%= ($is_party_on || false).to_s.html_safe %>
			let isLocked = <%= (is_locked? || false).to_s.html_safe %>
			let presetColors = <%= @preset_colors.to_json.html_safe %>
			$(document).ready(ready);
		</script>
	<% end %>
		<% if is_locked? && !is_admin? %>
			<div class='callout large primary'>
				<h2 class='flash-heading'>hueIT is locked</h2>
			</div>
		<% else %>
			<% if is_locked? %>
				<div class='callout large primary'>
					<h2 class='flash-heading'>hueIT is locked <%= "by #{locked_by}" if !locked_by.blank? %>, be mindful of what you change</h2>
				</div>
			<% end %>
			<% if $hue_not_found %>
				<div class='callout warning flash-heading'>
					<h3>Could not find Hue lights</h3><br>
					All data below is mocked for development purposes. Obviously requests to change the lights won't work.
				</div>
			<% end %>
			<div class='container'>
				<div class='content'>
					<%= render 'form' %>
				</div>
		</div>
		<% end %>
</main>